// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Methods.DataBase;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20260216163621_AddedIndexs")]
    partial class AddedIndexs
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.AddressesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Apartment")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Passport_Id")
                        .HasColumnType("int")
                        .HasColumnName("Passport_Id");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Passport_Id")
                        .HasDatabaseName("IX_Addresses_PassportId");

                    b.HasIndex("Country", "City", "Region", "Street", "House")
                        .HasDatabaseName("IX_Addresses_Full");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.ClientsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Passport_Id")
                        .HasColumnType("int")
                        .HasColumnName("Passport_Id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Clients_Email");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("IX_Clients_Login");

                    b.HasIndex("Passport_Id")
                        .HasDatabaseName("IX_Clients_PassportId");

                    b.HasIndex("Password")
                        .HasDatabaseName("IX_Clients_Password");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Clients_PhoneNumber");

                    b.HasIndex("SurName", "FirstName", "MiddleName")
                        .HasDatabaseName("IX_Clients_FullName");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.CurrencyRatesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DateReceipt")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("DigitalCode")
                        .HasColumnType("int");

                    b.Property<string>("LetterCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Currency")
                        .HasDatabaseName("IX_CurrencyRates_Currency");

                    b.HasIndex("LetterCode")
                        .HasDatabaseName("IX_CurrencyRates_LetterCode");

                    b.HasIndex("Rate")
                        .HasDatabaseName("IX_CurrencyRates_Rate");

                    b.ToTable("CurrencyRates");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.CurrencyRates_TicketsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrencyRates_Id")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyRates_Id");

                    b.Property<int?>("Tickets_Id")
                        .HasColumnType("int")
                        .HasColumnName("Tickets_Id");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyRates_Id")
                        .HasDatabaseName("IX_CurrencyRatesTickets_CurrencyRatesId");

                    b.HasIndex("Tickets_Id")
                        .HasDatabaseName("IX_CurrencyRatesTickets_TicketsId");

                    b.HasIndex("Tickets_Id", "CurrencyRates_Id")
                        .HasDatabaseName("IX_CurrencyRatesTickets_TicketsCurrencyRatesId");

                    b.ToTable("CurrencyRates_Tickets");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.EmployeesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Tickets_Id")
                        .HasColumnType("int")
                        .HasColumnName("Tickets_Id");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Employees_Email");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Employees_PhoneNumber");

                    b.HasIndex("Tickets_Id")
                        .HasDatabaseName("IX_Employees_TicketsId");

                    b.HasIndex("SurName", "FirstName", "MiddleName")
                        .HasDatabaseName("IX_Employees_FullName");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.HotelRoomsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("ImageRoom")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NameRoom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("NameRoom")
                        .HasDatabaseName("IX_HotelRooms_NameRoom");

                    b.ToTable("HotelRooms");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.HotelsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Address_Id")
                        .HasColumnType("int")
                        .HasColumnName("Address_Id");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("HotelRooms_Id")
                        .HasColumnType("int")
                        .HasColumnName("HotelRooms_Id");

                    b.Property<string>("ImageHotel")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<int?>("Tickets_Id")
                        .HasColumnType("int")
                        .HasColumnName("Tickets_Id");

                    b.Property<int>("TimeOfStay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Address_Id")
                        .HasDatabaseName("IX_Hotels_AddressId");

                    b.HasIndex("HotelRooms_Id")
                        .HasDatabaseName("IX_Hotels_HotelRoomsId");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Hotels_Name");

                    b.HasIndex("Tickets_Id")
                        .HasDatabaseName("IX_Hotels_TicketsId");

                    b.HasIndex("Tickets_Id", "Address_Id", "HotelRooms_Id")
                        .HasDatabaseName("IX_Hotels_TicketsAddressesRoomsId");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.PassportsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Seria")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Passports_Type");

                    b.HasIndex("Seria", "Number")
                        .IsUnique()
                        .HasDatabaseName("IX_Passports_Seria_Number");

                    b.ToTable("Passports");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.TicketsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int?>("Client_Id")
                        .HasColumnType("int")
                        .HasColumnName("Client_Id");

                    b.Property<DateTime>("DateSale")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Client_Id")
                        .HasDatabaseName("IX_Tickets_ClientId");

                    b.HasIndex("DateSale")
                        .HasDatabaseName("IX_Tickets_DateSale");

                    b.HasIndex("Price")
                        .HasDatabaseName("IX_Tickets_Price");

                    b.HasIndex("DepartureTime", "ArrivalTime")
                        .HasDatabaseName("IX_Tickets_Times");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.ToursModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("EndDot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageTour")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StartDot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Tickets_Id")
                        .HasColumnType("int")
                        .HasColumnName("Tickets_Id");

                    b.Property<int?>("Transfers_Id")
                        .HasColumnType("int")
                        .HasColumnName("Transfers_Id");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Tours_Name");

                    b.HasIndex("Tickets_Id")
                        .HasDatabaseName("IX_Tours_TicketsId");

                    b.HasIndex("Transfers_Id")
                        .HasDatabaseName("IX_Tours_TransfersId");

                    b.HasIndex("StartDot", "EndDot")
                        .HasDatabaseName("IX_Tours_Route");

                    b.HasIndex("Tickets_Id", "Transfers_Id")
                        .HasDatabaseName("IX_Tours_TicketsTransfersId");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.TransfersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Transfers_Name");

                    b.HasIndex("Route")
                        .HasDatabaseName("IX_Transfers_Route");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.AddressesModel", b =>
                {
                    b.HasOne("WebApi.Models.ModelsDataBase.PassportsModel", "Passport")
                        .WithMany("Addresses")
                        .HasForeignKey("Passport_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Passport");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.ClientsModel", b =>
                {
                    b.HasOne("WebApi.Models.ModelsDataBase.PassportsModel", "Passport")
                        .WithMany("Clients")
                        .HasForeignKey("Passport_Id")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.Navigation("Passport");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.CurrencyRates_TicketsModel", b =>
                {
                    b.HasOne("WebApi.Models.ModelsDataBase.CurrencyRatesModel", "CurrencyRate")
                        .WithMany("CurrencyRatesTickets")
                        .HasForeignKey("CurrencyRates_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApi.Models.ModelsDataBase.TicketsModel", "Ticket")
                        .WithMany("CurrencyRatesTickets")
                        .HasForeignKey("Tickets_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrencyRate");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.EmployeesModel", b =>
                {
                    b.HasOne("WebApi.Models.ModelsDataBase.TicketsModel", "Ticket")
                        .WithMany("Employees")
                        .HasForeignKey("Tickets_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.HotelsModel", b =>
                {
                    b.HasOne("WebApi.Models.ModelsDataBase.AddressesModel", "Address")
                        .WithMany("Hotels")
                        .HasForeignKey("Address_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApi.Models.ModelsDataBase.HotelRoomsModel", "HotelRoom")
                        .WithMany("Hotels")
                        .HasForeignKey("HotelRooms_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.ModelsDataBase.TicketsModel", "Ticket")
                        .WithMany()
                        .HasForeignKey("Tickets_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Address");

                    b.Navigation("HotelRoom");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.TicketsModel", b =>
                {
                    b.HasOne("WebApi.Models.ModelsDataBase.ClientsModel", "Client")
                        .WithMany("Tickets")
                        .HasForeignKey("Client_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Client");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.ToursModel", b =>
                {
                    b.HasOne("WebApi.Models.ModelsDataBase.TicketsModel", "Ticket")
                        .WithMany()
                        .HasForeignKey("Tickets_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApi.Models.ModelsDataBase.TransfersModel", "Transfer")
                        .WithMany("Tours")
                        .HasForeignKey("Transfers_Id")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ticket");

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.AddressesModel", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.ClientsModel", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.CurrencyRatesModel", b =>
                {
                    b.Navigation("CurrencyRatesTickets");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.HotelRoomsModel", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.PassportsModel", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.TicketsModel", b =>
                {
                    b.Navigation("CurrencyRatesTickets");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.TransfersModel", b =>
                {
                    b.Navigation("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
