// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Methods.DataBase;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20260508095515_UpdateNameTable2_1")]
    partial class UpdateNameTable2_1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.AddressesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Apartment")
                        .HasColumnType("int");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("House")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PassportId")
                        .HasColumnType("int")
                        .HasColumnName("PassportId");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("ToursId")
                        .HasColumnType("int")
                        .HasColumnName("ToursId");

                    b.HasKey("Id");

                    b.HasIndex("City")
                        .HasDatabaseName("IX_Addresses_City");

                    b.HasIndex("Country")
                        .HasDatabaseName("IX_Addresses_Country");

                    b.HasIndex("House")
                        .HasDatabaseName("IX_Addresses_House");

                    b.HasIndex("PassportId");

                    b.HasIndex("Region")
                        .HasDatabaseName("IX_Addresses_Region");

                    b.HasIndex("Street")
                        .HasDatabaseName("IX_Addresses_Street");

                    b.HasIndex("ToursId");

                    b.HasIndex("Country", "City", "Region", "Street", "House")
                        .HasDatabaseName("IX_Addresses_FullAddress");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.CurrencyRatesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DateReceipt")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("DigitalCode")
                        .HasColumnType("int");

                    b.Property<string>("LetterCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Currency")
                        .HasDatabaseName("IX_CurrencyRates_Currency");

                    b.HasIndex("DateReceipt")
                        .HasDatabaseName("IX_CurrencyRates_DateReceipt");

                    b.HasIndex("LetterCode")
                        .HasDatabaseName("IX_CurrencyRates_LetterCode");

                    b.HasIndex("Rate")
                        .HasDatabaseName("IX_CurrencyRates_Rate");

                    b.ToTable("CurrencyRates");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.CurrencyRates_TicketsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("CurrencyRatesId")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyRatesId");

                    b.Property<int?>("TicketsId")
                        .HasColumnType("int")
                        .HasColumnName("TicketsId");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyRatesId")
                        .HasDatabaseName("IX_CurrencyRatesTickets_CurrencyRatesId");

                    b.HasIndex("TicketsId")
                        .HasDatabaseName("IX_CurrencyRatesTickets_TicketsId");

                    b.HasIndex("TicketsId", "CurrencyRatesId")
                        .HasDatabaseName("IX_CurrencyRatesTickets_TicketsCurrencyRatesId");

                    b.ToTable("CurrencyRates_Tickets");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.HotelRoomsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("ImageRoom")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NameRoom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Details")
                        .HasDatabaseName("IX_HotelRooms_Details");

                    b.HasIndex("Floor")
                        .HasDatabaseName("IX_HotelRooms_Floor");

                    b.HasIndex("ImageRoom")
                        .HasDatabaseName("IX_HotelRooms_ImageRoom");

                    b.HasIndex("NameRoom")
                        .HasDatabaseName("IX_HotelRooms_NameRoom");

                    b.ToTable("HotelRooms");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.HotelsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("AddressId")
                        .HasColumnType("int")
                        .HasColumnName("AddressId");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("HotelRoomsId")
                        .HasColumnType("int")
                        .HasColumnName("HotelRoomsId");

                    b.Property<string>("ImageHotel")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<int?>("TicketsId")
                        .HasColumnType("int")
                        .HasColumnName("TicketsId");

                    b.Property<int>("TimeOfStay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("AddressId");

                    b.HasIndex("Details")
                        .HasDatabaseName("IX_Hotels_Details");

                    b.HasIndex("HotelRoomsId");

                    b.HasIndex("ImageHotel")
                        .HasDatabaseName("IX_Hotels_ImageHotel");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Hotels_Name");

                    b.HasIndex("Stars")
                        .HasDatabaseName("IX_Hotels_Stars");

                    b.HasIndex("TicketsId");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.PassportsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateOnly>("DateOfIssue")
                        .HasColumnType("date");

                    b.Property<string>("DepartmentCode")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<string>("IssuedBy")
                        .IsRequired()
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Seria")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.HasKey("Id");

                    b.HasIndex("DateOfIssue")
                        .HasDatabaseName("IX_Passports_DateOfIssue");

                    b.HasIndex("DepartmentCode")
                        .HasDatabaseName("IX_Passports_DepartmentCode");

                    b.HasIndex("IssuedBy")
                        .HasDatabaseName("IX_Passports_IssuedBy");

                    b.HasIndex("Number")
                        .IsUnique()
                        .HasDatabaseName("IX_Passports_Number");

                    b.HasIndex("Seria")
                        .IsUnique()
                        .HasDatabaseName("IX_Passports_Seria");

                    b.HasIndex("Type")
                        .HasDatabaseName("IX_Passports_Type");

                    b.HasIndex("Seria", "Number")
                        .IsUnique()
                        .HasDatabaseName("IX_Passports_Seria_Number");

                    b.ToTable("Passports");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.TicketsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DateSale")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("DateSale")
                        .HasDatabaseName("IX_Tickets_DateSale");

                    b.HasIndex("Price")
                        .HasDatabaseName("IX_Tickets_Price");

                    b.HasIndex("DepartureTime", "ArrivalTime")
                        .HasDatabaseName("IX_Tickets_Times");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.ToursModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(4000)
                        .HasColumnType("nvarchar(4000)");

                    b.Property<string>("EndDot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<bool>("HotTour")
                        .HasColumnType("bit");

                    b.Property<string>("ImageTour")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Included")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18, 2)");

                    b.Property<string>("Program")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Separately")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("StartDot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TicketsId")
                        .HasColumnType("int")
                        .HasColumnName("TicketsId");

                    b.Property<int?>("TransfersId")
                        .HasColumnType("int")
                        .HasColumnName("TransfersId");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Description")
                        .HasDatabaseName("IX_Tours_Description");

                    b.HasIndex("Details")
                        .HasDatabaseName("IX_Tours_Details");

                    b.HasIndex("HotTour")
                        .HasDatabaseName("IX_Tours_HotTour");

                    b.HasIndex("ImageTour")
                        .HasDatabaseName("IX_Tours_ImageTour");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Tours_Name");

                    b.HasIndex("Price")
                        .HasDatabaseName("IX_Tours_Price");

                    b.HasIndex("TicketsId");

                    b.HasIndex("TransfersId");

                    b.HasIndex("StartDot", "EndDot")
                        .HasDatabaseName("IX_Tours_Route");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.TransfersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Arrival")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Departure")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Arrival")
                        .HasDatabaseName("IX_Transfers_Arrival");

                    b.HasIndex("Departure")
                        .HasDatabaseName("IX_Transfers_Departure");

                    b.HasIndex("Name")
                        .HasDatabaseName("IX_Transfers_Name");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.UsersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Age")
                        .HasColumnType("int");

                    b.Property<DateOnly>("Birthday")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Gender")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<DateTime?>("LastLoginAt")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("LockoutEnd")
                        .HasColumnType("datetime2");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("LoginAttempts")
                        .HasColumnType("int");

                    b.Property<string>("MiddleName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("PassportId")
                        .HasColumnType("int")
                        .HasColumnName("PassportId");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RefreshToken")
                        .HasMaxLength(500)
                        .HasColumnType("nvarchar(500)");

                    b.Property<DateTime?>("RefreshTokenExpiryTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("Role")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("TicketsId")
                        .HasColumnType("int")
                        .HasColumnName("TicketsId");

                    b.HasKey("Id");

                    b.HasIndex("Age")
                        .HasDatabaseName("IX_Users_Age");

                    b.HasIndex("Birthday")
                        .HasDatabaseName("IX_Users_Birthday");

                    b.HasIndex("Email")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Email");

                    b.HasIndex("FirstName")
                        .HasDatabaseName("IX_Users_FirstName");

                    b.HasIndex("Gender")
                        .HasDatabaseName("IX_Users_Gender");

                    b.HasIndex("Login")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_Login");

                    b.HasIndex("MiddleName")
                        .HasDatabaseName("IX_Users_MiddleName");

                    b.HasIndex("PassportId");

                    b.HasIndex("PhoneNumber")
                        .IsUnique()
                        .HasDatabaseName("IX_Users_PhoneNumber");

                    b.HasIndex("Position")
                        .HasDatabaseName("IX_Users_Position");

                    b.HasIndex("Role")
                        .HasDatabaseName("IX_Users_Role");

                    b.HasIndex("SurName")
                        .HasDatabaseName("IX_Users_SurName");

                    b.HasIndex("TicketsId");

                    b.HasIndex("SurName", "FirstName", "MiddleName")
                        .HasDatabaseName("IX_Users_FullName");

                    b.ToTable("Users");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.AddressesModel", b =>
                {
                    b.HasOne("WebApi.Models.ModelsDataBase.PassportsModel", "Passport")
                        .WithMany("Addresses")
                        .HasForeignKey("PassportId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("WebApi.Models.ModelsDataBase.ToursModel", "Tours")
                        .WithMany("Addresses")
                        .HasForeignKey("ToursId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Passport");

                    b.Navigation("Tours");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.CurrencyRates_TicketsModel", b =>
                {
                    b.HasOne("WebApi.Models.ModelsDataBase.CurrencyRatesModel", "CurrencyRate")
                        .WithMany("CurrencyRatesTickets")
                        .HasForeignKey("CurrencyRatesId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApi.Models.ModelsDataBase.TicketsModel", "Ticket")
                        .WithMany("CurrencyRatesTickets")
                        .HasForeignKey("TicketsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("CurrencyRate");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.HotelsModel", b =>
                {
                    b.HasOne("WebApi.Models.ModelsDataBase.AddressesModel", "Address")
                        .WithMany("Hotels")
                        .HasForeignKey("AddressId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApi.Models.ModelsDataBase.HotelRoomsModel", "HotelRoom")
                        .WithMany("Hotels")
                        .HasForeignKey("HotelRoomsId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.ModelsDataBase.TicketsModel", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Address");

                    b.Navigation("HotelRoom");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.ToursModel", b =>
                {
                    b.HasOne("WebApi.Models.ModelsDataBase.TicketsModel", "Ticket")
                        .WithMany()
                        .HasForeignKey("TicketsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApi.Models.ModelsDataBase.TransfersModel", "Transfer")
                        .WithMany("Tours")
                        .HasForeignKey("TransfersId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Ticket");

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.UsersModel", b =>
                {
                    b.HasOne("WebApi.Models.ModelsDataBase.PassportsModel", "Passport")
                        .WithMany("Clients")
                        .HasForeignKey("PassportId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("WebApi.Models.ModelsDataBase.TicketsModel", "Ticket")
                        .WithMany("Users")
                        .HasForeignKey("TicketsId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Passport");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.AddressesModel", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.CurrencyRatesModel", b =>
                {
                    b.Navigation("CurrencyRatesTickets");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.HotelRoomsModel", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.PassportsModel", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.TicketsModel", b =>
                {
                    b.Navigation("CurrencyRatesTickets");

                    b.Navigation("Users");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.ToursModel", b =>
                {
                    b.Navigation("Addresses");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.TransfersModel", b =>
                {
                    b.Navigation("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
