// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using WebApi.Methods.DataBase;

#nullable disable

namespace WebApi.Migrations
{
    [DbContext(typeof(ServerDbContext))]
    [Migration("20260209191903_InitCreate")]
    partial class InitCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.12")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.AddressesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int?>("Apartment")
                        .HasColumnType("int");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("House")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int?>("Passport_Id")
                        .HasColumnType("int")
                        .HasColumnName("Passport_Id");

                    b.Property<string>("Region")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Street")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Passport_Id");

                    b.ToTable("Addresses");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.ClientsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Passport_Id")
                        .HasColumnType("int")
                        .HasColumnName("Passport_Id");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Passport_Id");

                    b.ToTable("Clients");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.CurrencyRatesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Currency")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("DateReceipt")
                        .IsRequired()
                        .HasMaxLength(25)
                        .HasColumnType("nvarchar(25)");

                    b.Property<int>("DigitalCode")
                        .HasColumnType("int");

                    b.Property<string>("LetterCode")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal>("Rate")
                        .HasColumnType("decimal(18,4)");

                    b.Property<int>("Units")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("CurrencyRates");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.CurrencyRates_TicketsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CurrencyRates_Id")
                        .HasColumnType("int")
                        .HasColumnName("CurrencyRates_Id");

                    b.Property<int>("Tickets_Id")
                        .HasColumnType("int")
                        .HasColumnName("Tickets_Id");

                    b.HasKey("Id");

                    b.HasIndex("CurrencyRates_Id");

                    b.HasIndex("Tickets_Id");

                    b.ToTable("CurrencyRates_Tickets");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.EmployeesModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("MiddleName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PhoneNumber")
                        .IsRequired()
                        .HasMaxLength(15)
                        .HasColumnType("nvarchar(15)");

                    b.Property<string>("Position")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SurName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tickets_Id")
                        .HasColumnType("int")
                        .HasColumnName("Tickets_Id");

                    b.HasKey("Id");

                    b.HasIndex("Tickets_Id");

                    b.ToTable("Employees");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.HotelRoomsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Floor")
                        .HasColumnType("int");

                    b.Property<string>("ImageRoom")
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("NameRoom")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.ToTable("HotelRoomsModels");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.HotelsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Address_Id")
                        .HasColumnType("int")
                        .HasColumnName("Address_Id");

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<int>("HotelRooms_Id")
                        .HasColumnType("int")
                        .HasColumnName("HotelRooms_Id");

                    b.Property<string>("ImageHotel")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Stars")
                        .HasColumnType("int");

                    b.Property<int>("Tickets_Id")
                        .HasColumnType("int")
                        .HasColumnName("Tickets_Id");

                    b.Property<int>("TimeOfStay")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("Address_Id");

                    b.HasIndex("HotelRooms_Id");

                    b.HasIndex("Tickets_Id");

                    b.ToTable("Hotels");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.PassportsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Number")
                        .HasColumnType("int");

                    b.Property<int>("Seria")
                        .HasColumnType("int");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.ToTable("Passports");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.TicketsModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("ArrivalTime")
                        .HasColumnType("datetime2");

                    b.Property<int>("Client_Id")
                        .HasColumnType("int")
                        .HasColumnName("Client_Id");

                    b.Property<DateTime>("DateSale")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("DepartureTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal>("Price")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("Client_Id");

                    b.ToTable("Tickets");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.ToursModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("EndDot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ImageTour")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("StartDot")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<int>("Tickets_Id")
                        .HasColumnType("int")
                        .HasColumnName("Tickets_Id");

                    b.Property<int>("Transfers_Id")
                        .HasColumnType("int")
                        .HasColumnName("Transfers_Id");

                    b.HasKey("Id");

                    b.HasIndex("Tickets_Id");

                    b.HasIndex("Transfers_Id");

                    b.ToTable("Tours");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.TransfersModel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Details")
                        .HasMaxLength(2000)
                        .HasColumnType("nvarchar(2000)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Route")
                        .IsRequired()
                        .HasMaxLength(1000)
                        .HasColumnType("nvarchar(1000)");

                    b.HasKey("Id");

                    b.ToTable("Transfers");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.AddressesModel", b =>
                {
                    b.HasOne("WebApi.Models.ModelsDataBase.PassportsModel", "Passport")
                        .WithMany("Addresses")
                        .HasForeignKey("Passport_Id")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Passport");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.ClientsModel", b =>
                {
                    b.HasOne("WebApi.Models.ModelsDataBase.PassportsModel", "Passport")
                        .WithMany("Clients")
                        .HasForeignKey("Passport_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Passport");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.CurrencyRates_TicketsModel", b =>
                {
                    b.HasOne("WebApi.Models.ModelsDataBase.CurrencyRatesModel", "CurrencyRate")
                        .WithMany("CurrencyRatesTickets")
                        .HasForeignKey("CurrencyRates_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.ModelsDataBase.TicketsModel", "Ticket")
                        .WithMany("CurrencyRatesTickets")
                        .HasForeignKey("Tickets_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("CurrencyRate");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.EmployeesModel", b =>
                {
                    b.HasOne("WebApi.Models.ModelsDataBase.TicketsModel", "Ticket")
                        .WithMany("Employees")
                        .HasForeignKey("Tickets_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.HotelsModel", b =>
                {
                    b.HasOne("WebApi.Models.ModelsDataBase.AddressesModel", "Address")
                        .WithMany("Hotels")
                        .HasForeignKey("Address_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.ModelsDataBase.HotelRoomsModel", "HotelRoom")
                        .WithMany("Hotels")
                        .HasForeignKey("HotelRooms_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.ModelsDataBase.TicketsModel", "Ticket")
                        .WithMany()
                        .HasForeignKey("Tickets_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Address");

                    b.Navigation("HotelRoom");

                    b.Navigation("Ticket");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.TicketsModel", b =>
                {
                    b.HasOne("WebApi.Models.ModelsDataBase.ClientsModel", "Client")
                        .WithMany("Tickets")
                        .HasForeignKey("Client_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Client");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.ToursModel", b =>
                {
                    b.HasOne("WebApi.Models.ModelsDataBase.TicketsModel", "Ticket")
                        .WithMany()
                        .HasForeignKey("Tickets_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("WebApi.Models.ModelsDataBase.TransfersModel", "Transfer")
                        .WithMany("Tours")
                        .HasForeignKey("Transfers_Id")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Ticket");

                    b.Navigation("Transfer");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.AddressesModel", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.ClientsModel", b =>
                {
                    b.Navigation("Tickets");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.CurrencyRatesModel", b =>
                {
                    b.Navigation("CurrencyRatesTickets");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.HotelRoomsModel", b =>
                {
                    b.Navigation("Hotels");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.PassportsModel", b =>
                {
                    b.Navigation("Addresses");

                    b.Navigation("Clients");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.TicketsModel", b =>
                {
                    b.Navigation("CurrencyRatesTickets");

                    b.Navigation("Employees");
                });

            modelBuilder.Entity("WebApi.Models.ModelsDataBase.TransfersModel", b =>
                {
                    b.Navigation("Tours");
                });
#pragma warning restore 612, 618
        }
    }
}
